[2023-06-13T06:59:05.683+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: condition_trigger_dag.check_condition manual__2023-06-13T06:59:03.997411+00:00 [queued]>
[2023-06-13T06:59:05.689+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: condition_trigger_dag.check_condition manual__2023-06-13T06:59:03.997411+00:00 [queued]>
[2023-06-13T06:59:05.691+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T06:59:05.694+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-06-13T06:59:05.695+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-13T06:59:05.703+0000] {taskinstance.py:1383} INFO - Executing <Task(BranchPythonOperator): check_condition> on 2023-06-13 06:59:03.997411+00:00
[2023-06-13T06:59:05.708+0000] {standard_task_runner.py:55} INFO - Started process 18151 to run task
[2023-06-13T06:59:05.713+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'condition_trigger_dag', 'check_condition', 'manual__2023-06-13T06:59:03.997411+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/condition_trigger_dag.py', '--cfg-path', '/tmp/tmps8l4oyvq']
[2023-06-13T06:59:05.714+0000] {standard_task_runner.py:83} INFO - Job 123: Subtask check_condition
[2023-06-13T06:59:05.772+0000] {task_command.py:376} INFO - Running <TaskInstance: condition_trigger_dag.check_condition manual__2023-06-13T06:59:03.997411+00:00 [running]> on host c0d3dfdc775c
[2023-06-13T06:59:05.828+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=condition_trigger_dag
AIRFLOW_CTX_TASK_ID=check_condition
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T06:59:03.997411+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-13T06:59:03.997411+00:00
[2023-06-13T06:59:05.830+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 211, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/condition_trigger_dag.py", line 13, in _check_condition
    value = ti.xcom_pull("my_key", task_ids = "t1")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got multiple values for argument 'task_ids'
[2023-06-13T06:59:05.842+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=condition_trigger_dag, task_id=check_condition, execution_date=20230613T065903, start_date=20230613T065905, end_date=20230613T065905
[2023-06-13T06:59:05.851+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 123 for task check_condition (xcom_pull() got multiple values for argument 'task_ids'; 18151)
[2023-06-13T06:59:05.884+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-13T06:59:05.918+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
