[2023-06-14T04:42:56.778+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: endToend_user_processing.is_api_available manual__2023-06-14T04:42:54.284962+00:00 [queued]>
[2023-06-14T04:42:56.785+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: endToend_user_processing.is_api_available manual__2023-06-14T04:42:54.284962+00:00 [queued]>
[2023-06-14T04:42:56.786+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T04:42:56.787+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-06-14T04:42:56.788+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T04:42:56.797+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-06-14 04:42:54.284962+00:00
[2023-06-14T04:42:56.802+0000] {standard_task_runner.py:55} INFO - Started process 646 to run task
[2023-06-14T04:42:56.807+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'endToend_user_processing', 'is_api_available', 'manual__2023-06-14T04:42:54.284962+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpeae6x4km']
[2023-06-14T04:42:56.811+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask is_api_available
[2023-06-14T04:42:56.870+0000] {task_command.py:376} INFO - Running <TaskInstance: endToend_user_processing.is_api_available manual__2023-06-14T04:42:54.284962+00:00 [running]> on host eccc8785320d
[2023-06-14T04:42:56.919+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=endToend_user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-06-14T04:42:54.284962+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-14T04:42:54.284962+00:00
[2023-06-14T04:42:56.922+0000] {http.py:120} INFO - Poking: api/
[2023-06-14T04:42:56.940+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 189, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 135, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 126, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 128, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 82, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2023-06-14T04:42:56.945+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=endToend_user_processing, task_id=is_api_available, execution_date=20230614T044254, start_date=20230614T044256, end_date=20230614T044256
[2023-06-14T04:42:56.953+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task is_api_available (The conn_id `user_api` isn't defined; 646)
[2023-06-14T04:42:56.979+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-14T04:42:57.010+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
