[2023-06-14T00:13:58.178+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: endToend_user_processing.create_table scheduled__2023-06-13T00:00:00+00:00 [queued]>
[2023-06-14T00:13:58.204+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: endToend_user_processing.create_table scheduled__2023-06-13T00:00:00+00:00 [queued]>
[2023-06-14T00:13:58.207+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T00:13:58.208+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-06-14T00:13:58.211+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T00:13:58.235+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-13 00:00:00+00:00
[2023-06-14T00:13:58.247+0000] {standard_task_runner.py:55} INFO - Started process 1126 to run task
[2023-06-14T00:13:58.267+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'endToend_user_processing', 'create_table', 'scheduled__2023-06-13T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8yzfsv1g']
[2023-06-14T00:13:58.277+0000] {standard_task_runner.py:83} INFO - Job 147: Subtask create_table
[2023-06-14T00:13:58.576+0000] {task_command.py:376} INFO - Running <TaskInstance: endToend_user_processing.create_table scheduled__2023-06-13T00:00:00+00:00 [running]> on host 5f3b9c67a0bc
[2023-06-14T00:13:58.870+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=endToend_user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-13T00:00:00+00:00
[2023-06-14T00:13:58.896+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-06-14T00:13:58.910+0000] {sql.py:315} INFO - Running statement: 
          Create table if not exists users (
               firstname TEXT NOT NULL,
               lastname TEXT NOT NULL,
               country TEXT NOT NULL,
               username TEXT NOT NULL,
               password TEXT NOT NULL,
               email TEXT NOT NULL
          );
        , parameters: None
[2023-06-14T00:13:58.922+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-06-14T00:13:58.936+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=endToend_user_processing, task_id=create_table, execution_date=20230613T000000, start_date=20230614T001358, end_date=20230614T001358
[2023-06-14T00:13:59.017+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-06-14T00:13:59.125+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-06-14T04:38:11.117+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: endToend_user_processing.create_table scheduled__2023-06-13T00:00:00+00:00 [queued]>
[2023-06-14T04:38:11.126+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: endToend_user_processing.create_table scheduled__2023-06-13T00:00:00+00:00 [queued]>
[2023-06-14T04:38:11.127+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T04:38:11.128+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-06-14T04:38:11.129+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-14T04:38:11.141+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-06-13 00:00:00+00:00
[2023-06-14T04:38:11.148+0000] {standard_task_runner.py:55} INFO - Started process 394 to run task
[2023-06-14T04:38:11.153+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'endToend_user_processing', 'create_table', 'scheduled__2023-06-13T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp9v7l6nsy']
[2023-06-14T04:38:11.156+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask create_table
[2023-06-14T04:38:11.245+0000] {task_command.py:376} INFO - Running <TaskInstance: endToend_user_processing.create_table scheduled__2023-06-13T00:00:00+00:00 [running]> on host eccc8785320d
[2023-06-14T04:38:11.341+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=endToend_user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-06-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-13T00:00:00+00:00
[2023-06-14T04:38:11.367+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-06-14T04:38:11.372+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=endToend_user_processing, task_id=create_table, execution_date=20230613T000000, start_date=20230614T043811, end_date=20230614T043811
[2023-06-14T04:38:11.383+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task create_table (The conn_id `postgres` isn't defined; 394)
[2023-06-14T04:38:11.410+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-14T04:38:11.438+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
